name: Deploy via Internal Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    environment: deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies & Deploy
        run: |
          cd /data1/team12
          if [ ! -d "ai-model" ]; then
            GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no" git clone git@github.com:NoSleep-Drive/ai-model.git
          else
            cd ai-model
            GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no" git pull origin main
          fi
