name: Deploy via Internal Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    environment: deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Configure Git Identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Clone or Pull Repository
        run: |
          set -e

          cd /data1/team12

          if [ -d "ai-model/.git" ]; then
            echo "Repository exists -> pulling latest changes..."
            cd ai-model
            GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no" git pull origin main
          else
            echo "Repository not found or not a git repo -> cloning from scratch"
            rm -rf ai-model 
            GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no" git clone git@github.com:NoSleep-Drive/ai-model.git
          fi

          echo "Model Deployment Ready"
